### ISSUE TITLE
Top level constant conflicts

### ISSUE THREAD

**Issue by snkashis** [PaymentRails/ruby-sdk#10]
I believe this current implementation, which uses `Gateway` and `Configuration`, as top level constants, is flawed, because any apps which currently have these classes defined... Will fail out...

I think the init of this  api client should be as simple as this
`client = PaymentRails.new('YOUR-API-KEY', 'YOUR-SECRET-KEY'`)
Only one top level constant exposed, `PaymentRails`

I believe a gem structure like https://github.com/hvssle/onfido would be better suited for something like this.

**Comment by koblas** [comment]
As a non-ruby person.  Having our API take over the global Gateway and Configuration names is really a bad idea.  @fronugget can you take a look

**Comment by snkashis** [comment]
Since this now appears resolved(https://github.com/PaymentRails/ruby-sdk/pull/11), are there plans to cut a new release soon?

**Comment by koblas** [comment]
@fronugget - Can you make sure the GEM gets updated

**Comment by snkashis** [comment]
Closed in https://github.com/PaymentRails/ruby-sdk/commit/ed554c0d2802724d5775c108378d60b9a706d62c

**Comment by snkashis** [comment]
@koblas And it appears we are not out of the water here yet. I just began using the newly released gem version containing these changes, and it appears constant usage is still mixed up. We have an AR model in our system called Recipient...and when I use `pr.recipient.search`...my class gets returned..not a PR class.

**Comment by snkashis** [comment]
@koblas are there plans to release a new version remedying this issue soon?

**Comment by fronugget** [comment]
@snkashis there is actually a pull request readdressing the issue, basically closely mirroring the architecture and module usage of the gem repo you mentioned. Should be merged in soon but take a look if you want incase you see anything funky

**Comment by snkashis** [comment]
@fronugget just tried pulling this branch in locally and your Recipient class is getting properly used now. Looks good to me
