### ISSUE TITLE
TypeError (no implicit conversion of nil into String):

### ISSUE THREAD

**Issue by perkins2099** [PaymentRails/ruby-sdk#15]
SDK Version 0.20
payload = {
:referenceId => "34",
:type => "business",
:name => "Adams Company",
:firstName => "fish",
:lastName => "frako",
:email => "fsd@asdfd.com",
:address => {
:street1 => "123 Main Street",
:street2 => "",
:postalCode => "53719",
:city => "Madison",
:country => "US",
:region => "Wisconsin",
:phone => "123-123-1234"
},
:payout => {
"accountNum" => "123",
"branchId" => "123",
"type" => "bank-transfer",
"currency" => "USD",
"country" => "US",
"accountHolderName" => "fish frako"
}
}

result = client.recipient.update(payment_rails_id, payload)

Error message TypeError (no implicit conversion of nil into String):

**Comment by fronugget** [comment]
Can't reproduce this with the same payload. Can you provide more context (payment_rails_id, ruby version, etc)?

Also worth noting that :payout => Object is not a recognized part of the recipient update body. You'll have to use client.recipient_account.(create or update) to manipulate payout methods directly. 

However, when creating a recipient (client.recipient.create) you can attach an :account => Object value, in place of your :payout one, and it will create a recipient with that payout method so long as the account information is correct.

**Comment by perkins2099** [comment]
Thanks for the clarification.  You have some old documentation with that "payout" object specified
https://docs.paymentrails.com/api/#recipient-attributes

:payment_rails_id => "R-RSDftzRsEs2ppky25vNDSu"
Ruby 2.5.3 
Rails 5.2.1
Thanks

**Comment by fronugget** [comment]
Documentation updated ;)

**Comment by perkins2099** [comment]
That wasn't the issue as im still getting this error

**Comment by fronugget** [comment]
Hmm.. I've copied your exact payload and am having no issues (other using Ruby 2.5.3. Try uninstalling the paymentrails gem and reinstalling it (maybe version is cached)
