### ISSUE TITLE
Creating payments with batch.create silently fails

### ISSUE THREAD

**Issue by snkashis** [PaymentRails/ruby-sdk#16]
My argument was `[{:recipient=>{:referenceId=>"SOME_REFERENCE_ID"}, :amount=>"SOME_AMOUNT", :memo=>"SOME_MEMO"}]`. Batch was created, payout was not

**Comment by fronugget** [comment]
API docs were outdated. Basically your payload is incorrectly formatted and the API will simply ignore unrecognized keys. Check the docs again as they've been updated.

**Comment by snkashis** [comment]
@fronugget okay, fixed my payload...and now when I try to specify the reference id as a string as the `id` key of `recipient`, i get `PaymentRails::MalformedException: Bad Request {"ok":false,"errors":[{"code":"invalid_field","message":"recipient does not exist","field":"recipient"}]}`..if I try it as a straight integer, i get `PaymentRails::ServerError: Internal Server Error {"ok":false,"errors":[{"code":500,"message":"internal_error"}]}`. All my reference ids are simply plain integers. I have confirmed I do have a recipient with this reference id present. When I try creating the batch with this person's Payment Rails internal id, it works fine.

**Comment by snkashis** [comment]
Got it, thanks for clarification. Will you consider PR that validates required/optional keys?

**Comment by fronugget** [comment]
Definitely considered for the future, thanks :)
